version: '3'
services:
  data_anally_project:
    restart: always
    build: .
    container_name: 'youtube_anally_container'
    working_dir: '/root/opt/'
    tty: true
    volumes:
      - ./opt:/root/opt
